# Generated by Django 5.1.1 on 2024-11-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_delivery_payment_alter_namespecification_options_and_more"),
        ("comparison", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="Comparison product",
            ),
        ),
    ]
