# Generated by Django 5.1.1 on 2024-11-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline_data", models.DateField(verbose_name="Deadline Date")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created_date"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
