# Generated by Django 5.1.1 on 2024-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("success", "Успешно"), ("failed", "Неуспешно")], max_length=7)),
                ("details", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
