# Generated by Django 5.1.1 on 2024-11-16 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_importlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importlog",
            name="created_at",
        ),
        migrations.AddField(
            model_name="importlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importlog",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
