# Generated by Django 5.1.1 on 2024-11-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PP", "В пункт выдачи"),
                            ("CR", "Курьером"),
                            ("LK", "В постамат"),
                            ("SL", "Силами продавца"),
                        ],
                        default="PP",
                        max_length=2,
                        verbose_name="Delivery method",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CH", "Наличными"),
                            ("CO", "Картой онлайн"),
                            ("CC", "Картой курьеру"),
                        ],
                        default="CH",
                        max_length=2,
                        verbose_name="Payment method",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="namespecification",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="product",
            name="view",
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Views"),
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="delivery_methods",
            field=models.ManyToManyField(
                to="catalog.delivery", verbose_name="Delivery methods"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="payment_methods",
            field=models.ManyToManyField(
                to="catalog.payment", verbose_name="Payment methods"
            ),
        ),
    ]
