# Generated by Django 5.1.1 on 2024-11-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0013_customuser_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_city",
                    models.CharField(max_length=255, verbose_name="Delivery city"),
                ),
                (
                    "delivery_address",
                    models.TextField(max_length=500, verbose_name="Delivery address"),
                ),
                ("comment", models.TextField(max_length=1000, verbose_name="Comment")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANKNOTES", "Banknotes"),
                            ("CARD", "Bank card"),
                            ("ONLINE", "Online payment"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("COURIER", "Courier"),
                            ("PICKUP", "Pickup"),
                            ("POST", "Postal service"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="auth.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
        ),
    ]
